export * from './PaymentsContent';
export * from './PaymentsCards';
export * from './PaymentsCategories';
export * from './PaymentsCategoriesBox';
export * from './PaymentsButton';
export * from './PaymentsATM';
export * from './PaymentsBankBranch';
export * from './PaymentsNews';
export * from './PaymentsTabs';